### ISSUE TITLE
Comments not working when logger++ is enabled

### ISSUE THREAD

**Issue by 0xm4v3rick** [synfron/ReshaperForBurp#27]
@ddwightx First of thanks for the awesome plugin.

When I have logger++ enabled reshaper is not able to add comment based on the created rules. Adding video that should clarify the issue. However I am not sure if this is LPP issue or reshaper or I am doing something wrong. 

- I have tried resetting the LPP settings.
- The reshaper rule set up to add a comment is based on the presence of parameter in inscope request.
- I am using burp pro v2022.8.1

Let me know if any more details are required

https://user-images.githubusercontent.com/29249263/185191443-73bb8639-4d0b-4086-a71d-9d4a229a104b.mp4

.

**Comment by ddwightx** [comment]
@0xm4v3rick I'm glad you like the plugin!

Unfortunately this is due to Logger++ using comments seemingly to match the response with the request that originally sent it. See [the code here](https://github.com/nccgroup/LoggerPlusPlus/blob/master/src/main/java/com/nccgroup/loggerplusplus/logview/processor/LogProcessorHelper.java). 

You can may be able to have Reshaper be the last one to set the comment (therefore overwrite the comment set by Logger++) by changing the order that the plugins are listed in the Burp Extender > Extensions tab and relaunching Burp, however overwriting the comment Logger++ sets might break Logger++'s response handling.

**Comment by 0xm4v3rick** [comment]
Well that's unfortunate. 
Workaround that you have suggested is working for now. Thanks for having a look.

Would you suggest opening up a issue with LPP for them to have a look at this?
Thanks!

**Comment by ddwightx** [comment]
It may be a good idea so at least they are informed that their usage of the comments may deserve some looking into to maybe provide alternative options. The root problem is that Burp's extension API does not provide an ID system to allow extensions to be able to map requests and responses. So that's where a true enhancement is needed. 

That being said,  if Logger++ wanted to be more friendly to other usages of comments,  it could append their ID to the comment rather than completely overwrite it.

**Comment by 0xm4v3rick** [comment]
Thanks, appreciate the help. I will open up an issue on LPP and close this.

**Comment by CoreyD97** [comment]
Hey! Just an update here: Logger++ has always written comments in a way that should not overwrite comments from other extensions, and worked well (as far as I know) for the last few years. This issue started around the same time PortSwigger started making changes to the underlying API (which actually broke a couple of other things too), so I think this might have been due to an API change. I'm working on a new version using the Montoya API already, and hope to have a better way of matching requests and responses than using comments.

**Comment by ddwightx** [comment]
@CoreyD97  Thanks for the update.
