### ISSUE TITLE
Replace Binary Content

### ISSUE THREAD

**Issue by rob-ip** [synfron/ReshaperForBurp#52]
I'm attempting to use `Run Process` in a rule in order to replace a response for a certain URL with my own content.

I've set `Command` as

`dd if=/path/to/file.bin`

and the result is stored in an `Event` variable.

However, I notice the `Set Value` `Then` only allows the source to be `Text`, `JSON`, `HTML` or `Params` and there's no binary option. Currently my replace breaks as if I test by substituting the exact same binary file, the `Content-Length` is different, suggesting the data is parsed as text encoding.

Is there a way I can read a file as binary and set it in the response body? Thanks

**Comment by ddwightx** [comment]
At the moment  `Run Process` won't work well for reading in binary. Also, in my testing I see `dd if=<filepath>` adds transfer details text to the end of the stdout, which would also effect the accuracy of the bytes.

Instead, I recommend using a [file variable tag](https://synfron.github.io/ReshaperForBurp/Variables.html#:~:text=File%20Variable) (i.e. `{{f:Default:/path/to/file.bin}}`) instead of the Event variable or `Read File` to read the file into an `Event` variable.

**Comment by rob-ip** [comment]
Thanks - I was attempting to make this dynamic like [here](https://github.com/synfron/ReshaperForBurp/issues/43#issuecomment-1735738215).

However, as I only have a handful of binaries I need to override `{{f:Default:/path/to/file.bin}}` should be fine.

Cheers for being so responsive.

**Comment by ddwightx** [comment]
@rob-ip Ah Ok, if you need to be more dynamic, you can use Then Read File which is available on the latest version of Reshaper.
